// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function DeleteSchedule(arg1) {
  return window['go']['main']['App']['DeleteSchedule'](arg1);
}

export function DeleteServer(arg1) {
  return window['go']['main']['App']['DeleteServer'](arg1);
}

export function DeleteWatch(arg1) {
  return window['go']['main']['App']['DeleteWatch'](arg1);
}

export function GenerateKeyPair() {
  return window['go']['main']['App']['GenerateKeyPair']();
}

export function GetDataDir() {
  return window['go']['main']['App']['GetDataDir']();
}

export function GetFileInfo(arg1) {
  return window['go']['main']['App']['GetFileInfo'](arg1);
}

export function GetHistory(arg1) {
  return window['go']['main']['App']['GetHistory'](arg1);
}

export function GetKeyPair() {
  return window['go']['main']['App']['GetKeyPair']();
}

export function GetPublicKeyFromPrivate(arg1) {
  return window['go']['main']['App']['GetPublicKeyFromPrivate'](arg1);
}

export function GetSchedules() {
  return window['go']['main']['App']['GetSchedules']();
}

export function GetServerInfo(arg1) {
  return window['go']['main']['App']['GetServerInfo'](arg1);
}

export function GetServers() {
  return window['go']['main']['App']['GetServers']();
}

export function GetWatches() {
  return window['go']['main']['App']['GetWatches']();
}

export function SaveKeyPair(arg1) {
  return window['go']['main']['App']['SaveKeyPair'](arg1);
}

export function SaveSchedule(arg1) {
  return window['go']['main']['App']['SaveSchedule'](arg1);
}

export function SaveServer(arg1) {
  return window['go']['main']['App']['SaveServer'](arg1);
}

export function SaveWatch(arg1) {
  return window['go']['main']['App']['SaveWatch'](arg1);
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function SetDefaultServer(arg1) {
  return window['go']['main']['App']['SetDefaultServer'](arg1);
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}

export function UploadFile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UploadFile'](arg1, arg2, arg3, arg4);
}
