// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';
import {main} from '../models';

export function ClearHistory():Promise<void>;

export function DeleteSchedule(arg1:string):Promise<void>;

export function DeleteServer(arg1:string):Promise<void>;

export function DeleteWatch(arg1:string):Promise<void>;

export function GenerateKeyPair():Promise<Record<string, string>>;

export function GetDataDir():Promise<string>;

export function GetFileInfo(arg1:string):Promise<Record<string, any>>;

export function GetHistory(arg1:number):Promise<Array<database.HistoryEntry>>;

export function GetKeyPair():Promise<database.KeyPair>;

export function GetPublicKeyFromPrivate(arg1:string):Promise<string>;

export function GetSchedules():Promise<Array<database.Schedule>>;

export function GetServerInfo(arg1:string):Promise<Record<string, any>>;

export function GetServers():Promise<Array<database.Server>>;

export function GetWatches():Promise<Array<database.WatchConfig>>;

export function SaveKeyPair(arg1:string):Promise<void>;

export function SaveSchedule(arg1:database.Schedule):Promise<void>;

export function SaveServer(arg1:database.Server):Promise<void>;

export function SaveWatch(arg1:database.WatchConfig):Promise<void>;

export function SelectFile():Promise<string>;

export function SelectFolder():Promise<string>;

export function SetDefaultServer(arg1:string):Promise<void>;

export function TestConnection(arg1:string):Promise<void>;

export function UploadFile(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<main.UploadResultWrapper>;
